DELIMITER //

CREATE FUNCTION calcNetSalaryBG(dGrossSalary DECIMAL) RETURNS DECIMAL(10,2)
  NO SQL
  DETERMINISTIC
BEGIN
  RETURN calcNetSalaryBGForYear(dGrossSalary, YEAR(NOW()));
END //

DELIMITER ;
